use serde::{Deserialize, Serialize};

/// A single change record. Generated by the client on every mutation,
/// pushed to the server, and pulled/applied by other clients.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChangelogEntry {
    pub id: Option<i64>,
    pub table_name: String,
    pub row_id: String,
    pub operation: String,
    pub payload: String,
    pub client_ts: i64,
    pub server_ts: Option<i64>,
    pub synced: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPushRequest {
    pub device_id: String,
    pub last_server_ts: i64,
    pub entries: Vec<ChangelogEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPushResponse {
    pub accepted: Vec<SyncAck>,
    pub conflicts: Vec<ChangelogEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncAck {
    pub client_entry_id: i64,
    pub server_ts: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPullRequest {
    pub device_id: String,
    pub last_server_ts: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPullResponse {
    pub entries: Vec<ChangelogEntry>,
    pub latest_server_ts: i64,
}

/// Supported sync operations
pub const OP_INSERT: &str = "insert";
pub const OP_UPDATE: &str = "update";
pub const OP_DELETE: &str = "delete";

/// Tables that participate in sync
pub const SYNC_TABLES: &[&str] = &["tasks", "task_columns", "task_groups", "notes", "schedules"];
